### PR TITLE
fix: GetTransactionNoWalletResponse.transaction: allow null and expor…

### PR DESCRIPTION
**Pull request by you21979**
1. call GetTransactionNoWallet with includeTransaction=false result transaction is null.
2. I want to export the interface when creating data.

### CODE REVIEW

**Comment by junderw** [comment]
@d-yokoi What is the convention for exporting interfaces? a lot of these smaller interfaces are only split up for readability (nested interfaces are ugly) so exporting everything seems like it would increase confusion (exported interfaces are important, non-exported are not etc.)

I leave the decision up to you.

re: transaction null LGTM ACK

**Comment by junderw** [comment]
Decided to just export everything from index

**Comment by junderw** [comment]
tests passed locally. merging

**Comment by d-yokoi** [comment]
In my experience, it's good to export all interfaces which are visible to users.
However, only types exported at the index file should be under official support so we can change others without announcement.

**Comment by you21979** [comment]
thank you merge it.

**Pull request merged**
